# <font color='blue'>Instituto Fedral de São Paulo - Fundamentos da Ciências de Dados</font>

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

# Meu setup local, criar um abiente de trabalho virtual python e instalar os pacoter requeridos no ambiente.

# abra um terminal e use os seguintes comandos

# criar um ambiente de trabalho virtual python:
python3 -m venv venv

# ativar o ambiente de trabalho virtual:
source venv/bin/activate

# instalar as dependencias do projeto
pip install -r requirements.txt

# para desativar o ambiente virtual use o comando:
deactivate

### Exercício 1

In [ ]:
# Crie um array NumPy com o número 1000000 e uma lista com o número 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de 
# execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

In [2]:
import numpy as np

# Crie um array NumPy com o número 1000000
numpy_array = np.arange(1000000)

# Crie uma lista com o número 1000000
python_list = list(range(1000000))

# Multiplique cada elemento do array por 2 e calcule o tempo de execução
print("Tempo de execução para array NumPy:")
%time numpy_array = numpy_array * 2

# Multiplique cada elemento da lista por 2 e calcule o tempo de execução
print("Tempo de execução para lista:")
%time python_list = [x * 2 for x in python_list]

# O array NumPy oferece melhor performance


Tempo de execução para array NumPy:
CPU times: user 0 ns, sys: 2.49 ms, total: 2.49 ms
Wall time: 2.35 ms
Tempo de execução para lista:
CPU times: user 35.4 ms, sys: 24.9 ms, total: 60.2 ms
Wall time: 60.2 ms


### Exercício 2

In [ ]:
# Exercício 2
# Crie um array numpy de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [3]:
import numpy as np

# Criar um array numpy de 10 elementos
arr = np.arange(10)
print("Array original:", arr)

# Alterar os valores de todos os elementos dos índices 5 a 8 para 0
arr[5:9] = 0
print("Array atualizado:", arr)


Array original: [0 1 2 3 4 5 6 7 8 9]
Array atualizado: [0 1 2 3 4 0 0 0 0 9]


### Exercício 3

In [ ]:
# Crie um array numpy de 3 dimensões e imprima a dimensão 1 

In [4]:
# Criar um array NumPy 3D
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Imprimir o array 3D
print("Array 3D:\n", array_3d)

# Imprimir a forma do array 3D
print("\nForma do array 3D:", array_3d.shape)

# Imprimir a dimensão 1 do array 3D
print("\nDimensão 1 do array 3D:\n", array_3d[0])

Array 3D:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Forma do array 3D: (2, 2, 3)

Dimensão 1 do array 3D:
 [[1 2 3]
 [4 5 6]]


### Exercício 4

In [ ]:
# Crie um array numpy de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda 
# e terceira colunas

In [5]:
# Criar uma matriz NumPy bidimensional
matriz = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Imprimir os elementos da terceira linha da matriz
print("Terceira linha da matriz:")
print(matriz[2, :])  # Imprime todos os elementos da terceira linha (índice 2)

# Imprimir todos os elementos da primeira e segunda linhas e segunda e terceira colunas
print("\nElementos da primeira e segunda linhas e segunda e terceira colunas:")
print(matriz[0:2, 1:3])  # Imprime os elementos das linhas 0 e 1 (primeira e segunda linhas) e colunas 1 e 2 (segunda e terceira colunas)


Terceira linha da matriz:
[ 9 10 11 12]

Elementos da primeira e segunda linhas e segunda e terceira colunas:
[[2 3]
 [6 7]]


### Exercício 5

In [ ]:
# Crie uma matriz de 15 números com 3 linhas 5 colunas utilizando numpy
# Utilize o métodos arange() para criar a matriz e reshape() para dimensioná-la
# Em seguida, calcule a matriz transposta dessa matriz.

In [6]:
# Criar uma matriz 3x5 com números de 0 a 14
matriz_original = np.arange(15).reshape(3, 5)

# Calcular a matriz transposta
matriz_transposta = matriz_original.T

# Imprimir a matriz original
print("Matriz Original:")
print(matriz_original)

# Imprimir a matriz transposta
print("\nMatriz Transposta:")
print(matriz_transposta)

Matriz Original:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Matriz Transposta:
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### Exercício 6

In [ ]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. 
# Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [7]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

resultado = np.where(cond, xarr, yarr)
print(resultado)

[1.1 2.2 1.3 1.4 2.5]


### Exercício 7

In [ ]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy.
# O arqquivo .npy é utilizado para armazenar arrays do NumPy (numpy.ndarray) 
# de forma eficiente preservando os dados e o formato do array.
# Depois carregue o array do disco no array B.

In [8]:
# Criar um array A com 10 elementos
A = np.arange(10)

# Salvar o array A em disco com a extensão .npy
np.save('array_A.npy', A)

# Carregar o array do disco no array B
B = np.load('array_A.npy')

# Imprimir o array B para verificar
print(B)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [ ]:
# Considerando a série abaixo, imprima os valores únicos na série, ou seja,
# aqueles que não se repetem.
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [9]:
import pandas as pd

obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

# Use value_counts() para contar a frequência de cada valor
value_counts = obj.value_counts()

# Filtre os valores que aparecem apenas uma vez
unique_values = value_counts[value_counts == 1].index

# Imprima os valores únicos
print("Valores únicos na série:")
for value in unique_values:
    print(value)


Valores únicos na série:
d


### Exercício 9

In [ ]:
# O trecho de código a seguir, conecta em uma url na internet, 
# que acessa e baixa um dataset da internet.
# Exiba os dados das colunas 'number', 'title', 'labels', 'state'
# do dataframe conforme a seguir.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

In [11]:
import requests
import pandas as pd

url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)

if resp.status_code == 200:
    issues = resp.json()
    df = pd.DataFrame(issues)
    print(df[['number', 'title', 'labels', 'state']])
else:
    print(f"Request failed with status code: {resp.status_code}")


    number                                              title  \
0    61394  DOC: add `api.types.is_dtype_equal` into document   
1    61393  Subplot title count fix + fix for issue introd...   
2    61392  DOC: Issue with the general expressiveness of ...   
3    61391  fix MultiIndex.difference not working with PyA...   
4    61389  BUG: Incorrect Parsing of Timestamps in pd.to_...   
5    61387       TYP:  `npt._ArrayLikeInt_co`  does not exist   
6    61386  ENH: read_csv with usecols shouldn't change co...   
7    61385                 BUG: to_sql works only for strings   
8    61384  BLD: Try using shared memory utilities in Cyth...   
9    61383                 ENH: Implement pandas.read_iceberg   
10   61382  BUG: Multindex difference not working on colum...   
11   61381  Fix alignment in Series subtraction with Multi...   
12   61380  Update CI to include Translations from Scienti...   
13   61378  DOC: update pandas cheat sheet with a third pa...   
14   61372           Fix 

### Exercício 10

In [ ]:
# Crie um dicionário python com 5 linguagens, de programação, 
# a quantidade de usuários dessas linguagens nos estados unidos 
# e o ano de lançamento de cada uma delas, onde, a chave serão 
# as linguagens de programação e os valores como listas python 
# desse dicionário.
# linguagens: Python, JavaScript, Java, C#, C++
# Ano de Lançamento: 1991, 1995, 1995, 2000, 1985
# Qtde. Usuários: 8000000, 7500000, 5000000, 3000000, 2500000


In [12]:
# Criando o dicionário com linguagens de programação
linguagens_programacao = {
    "Python": [8000000, 1991],
    "JavaScript": [7500000, 1995],
    "Java": [5000000, 1995],
    "C#": [3000000, 2000],
    "C++": [2500000, 1985]
}

# Exibindo o dicionário
print(linguagens_programacao)


{'Python': [8000000, 1991], 'JavaScript': [7500000, 1995], 'Java': [5000000, 1995], 'C#': [3000000, 2000], 'C++': [2500000, 1985]}


In [ ]:
# Converta o dicionário em um dataframe

In [13]:
import pandas as pd

# Criando o dicionário com linguagens de programação
linguagens_programacao = {
    "Python": [8000000, 1991],
    "JavaScript": [7500000, 1995],
    "Java": [5000000, 1995],
    "C#": [3000000, 2000],
    "C++": [2500000, 1985]
}

# Convertendo o dicionário em um DataFrame
df = pd.DataFrame.from_dict(linguagens_programacao, orient='index', columns=['Quantidade de Usuários', 'Ano de Lançamento'])

# Resetando o índice para que as linguagens sejam uma coluna
df.reset_index(inplace=True)
df.rename(columns={'index': 'Linguagem'}, inplace=True)

# Exibindo o DataFrame
print(df)


    Linguagem  Quantidade de Usuários  Ano de Lançamento
0      Python                 8000000               1991
1  JavaScript                 7500000               1995
2        Java                 5000000               1995
3          C#                 3000000               2000
4         C++                 2500000               1985


In [ ]:
# Converta no dataframe linhas em colunas e colunas em linhas.

In [14]:
import pandas as pd

# Criando o dicionário com linguagens de programação
linguagens_programacao = {
    "Python": [8000000, 1991],
    "JavaScript": [7500000, 1995],
    "Java": [5000000, 1995],
    "C#": [3000000, 2000],
    "C++": [2500000, 1985]
}

# Convertendo o dicionário em um DataFrame
df = pd.DataFrame.from_dict(linguagens_programacao, orient='index', columns=['Quantidade de Usuários', 'Ano de Lançamento'])

# Resetando o índice para que as linguagens sejam uma coluna
df.reset_index(inplace=True)
df.rename(columns={'index': 'Linguagem'}, inplace=True)

# Transpondo o DataFrame
df_transposto = df.T

# Exibindo o DataFrame transposto
print(df_transposto)


                              0           1        2        3        4
Linguagem                Python  JavaScript     Java       C#      C++
Quantidade de Usuários  8000000     7500000  5000000  3000000  2500000
Ano de Lançamento          1991        1995     1995     2000     1985


In [ ]:
# Altere os títulos das colunas para Qtde Usuarios e Ano

In [17]:
import pandas as pd

# Criando o dicionário com linguagens de programação
linguagens_programacao = {
    "Python": [8000000, 1991],
    "JavaScript": [7500000, 1995],
    "Java": [5000000, 1995],
    "C#": [3000000, 2000],
    "C++": [2500000, 1985]
}

# Convertendo o dicionário em um DataFrame
df = pd.DataFrame.from_dict(linguagens_programacao, orient='index', columns=['Quantidade de Usuários', 'Ano de Lançamento'])

# Resetando o índice para que as linguagens sejam uma coluna
df.reset_index(inplace=True)
df.rename(columns={'index': 'Linguagem'}, inplace=True)

# Alterando os títulos das colunas
df.columns = ['Linguagem', 'Qtde Usuarios', 'Ano']

# Exibindo o DataFrame com os novos títulos
print(df)


    Linguagem  Qtde Usuarios   Ano
0      Python        8000000  1991
1  JavaScript        7500000  1995
2        Java        5000000  1995
3          C#        3000000  2000
4         C++        2500000  1985


In [ ]:
# Exiba o tipo de dado de cada coluna. 

In [18]:
import pandas as pd

# Criando o dicionário com linguagens de programação
linguagens_programacao = {
    "Python": [8000000, 1991],
    "JavaScript": [7500000, 1995],
    "Java": [5000000, 1995],
    "C#": [3000000, 2000],
    "C++": [2500000, 1985]
}

# Convertendo o dicionário em um DataFrame
df = pd.DataFrame.from_dict(linguagens_programacao, orient='index', columns=['Quantidade de Usuários', 'Ano de Lançamento'])

# Resetando o índice para que as linguagens sejam uma coluna
df.reset_index(inplace=True)
df.rename(columns={'index': 'Linguagem'}, inplace=True)

# Alterando os títulos das colunas
df.columns = ['Linguagem', 'Qtde Usuarios', 'Ano']

# Exibindo o tipo de dado de cada coluna
tipos_dados = df.dtypes
print(tipos_dados)


Linguagem        object
Qtde Usuarios     int64
Ano               int64
dtype: object


In [ ]:
# Visualize as 5 primeiras linhas do dataframe

In [19]:
import pandas as pd

# Criando o dicionário com linguagens de programação
linguagens_programacao = {
    "Python": [8000000, 1991],
    "JavaScript": [7500000, 1995],
    "Java": [5000000, 1995],
    "C#": [3000000, 2000],
    "C++": [2500000, 1985]
}

# Convertendo o dicionário em um DataFrame
df = pd.DataFrame.from_dict(linguagens_programacao, orient='index', columns=['Quantidade de Usuários', 'Ano de Lançamento'])

# Resetando o índice para que as linguagens sejam uma coluna
df.reset_index(inplace=True)
df.rename(columns={'index': 'Linguagem'}, inplace=True)

# Alterando os títulos das colunas
df.columns = ['Linguagem', 'Qtde Usuarios', 'Ano']

# Visualizando as 5 primeiras linhas do DataFrame
print(df.head())


    Linguagem  Qtde Usuarios   Ano
0      Python        8000000  1991
1  JavaScript        7500000  1995
2        Java        5000000  1995
3          C#        3000000  2000
4         C++        2500000  1985


### Exercício 11

In [ ]:
# Usando o método read_csv do pandas e carregue o arquivo salarios.csv
# Este método exige-se que se coloque o separador vírgula ',' 
# no parâmetro sep.


In [20]:
import pandas as pd

# Carregando o arquivo salarios.csv
df_salarios = pd.read_csv('salarios.csv', sep=',')

# Exibindo as 5 primeiras linhas do DataFrame
print(df_salarios.head())


                  Name            Position Title        Department  \
0      AARON,  ELVIA J          WATER RATE TAKER       WATER MGMNT   
1    AARON,  JEFFERY M            POLICE OFFICER            POLICE   
2       AARON,  KARINA            POLICE OFFICER            POLICE   
3  AARON,  KIMBERLEI R  CHIEF CONTRACT EXPEDITER  GENERAL SERVICES   
4  ABAD JR,  VICENTE M         CIVIL ENGINEER IV       WATER MGMNT   

  Employee Annual Salary  
0              $88968.00  
1              $80778.00  
2              $80778.00  
3              $84780.00  
4             $104736.00  


In [ ]:
# Verifique se as colunas do dataframe possuem valores ausentes.


In [21]:
import pandas as pd

# Carregando o arquivo salarios.csv
df_salarios = pd.read_csv('salarios.csv', sep=',')

# Verificando se as colunas possuem valores ausentes
valores_ausentes = df_salarios.isnull().sum()

# Exibindo a contagem de valores ausentes por coluna
print(valores_ausentes)


Name                      1
Position Title            1
Department                1
Employee Annual Salary    1
dtype: int64


In [ ]:
# Remova do datafrane a linha cujo índice é o número 32181


In [22]:
import pandas as pd

# Carregando o arquivo salarios.csv
df_salarios = pd.read_csv('salarios.csv', sep=',')

# Removendo a linha cujo índice é 32181
df_salarios = df_salarios.drop(index=32181)

# Exibindo as 5 primeiras linhas do DataFrame após a remoção
print(df_salarios.head())


                  Name            Position Title        Department  \
0      AARON,  ELVIA J          WATER RATE TAKER       WATER MGMNT   
1    AARON,  JEFFERY M            POLICE OFFICER            POLICE   
2       AARON,  KARINA            POLICE OFFICER            POLICE   
3  AARON,  KIMBERLEI R  CHIEF CONTRACT EXPEDITER  GENERAL SERVICES   
4  ABAD JR,  VICENTE M         CIVIL ENGINEER IV       WATER MGMNT   

  Employee Annual Salary  
0              $88968.00  
1              $80778.00  
2              $80778.00  
3              $84780.00  
4             $104736.00  


In [ ]:
# Exiba os tipos de dados de cada coluna do dataframe


In [23]:
import pandas as pd

# Carregando o arquivo salarios.csv
df_salarios = pd.read_csv('salarios.csv', sep=',')

# Exibindo os tipos de dados de cada coluna
tipos_dados = df_salarios.dtypes
print(tipos_dados)


Name                      object
Position Title            object
Department                object
Employee Annual Salary    object
dtype: object


In [ ]:
# Remova o caractere $ dos valores da coluna Employee Annual Salary e
# Converta a coluna Employee Annual Salary para tipo float.


In [24]:
import pandas as pd

# Carregando o arquivo salarios.csv
df_salarios = pd.read_csv('salarios.csv', sep=',')

# Removendo o caractere $ e convertendo para float
df_salarios['Employee Annual Salary'] = df_salarios['Employee Annual Salary'].str.replace('$', '', regex=False).astype(float)

# Exibindo os tipos de dados de cada coluna após a conversão
tipos_dados = df_salarios.dtypes
print(tipos_dados)

# Exibindo as 5 primeiras linhas do DataFrame para verificar a alteração
print(df_salarios.head())


Name                       object
Position Title             object
Department                 object
Employee Annual Salary    float64
dtype: object
                  Name            Position Title        Department  \
0      AARON,  ELVIA J          WATER RATE TAKER       WATER MGMNT   
1    AARON,  JEFFERY M            POLICE OFFICER            POLICE   
2       AARON,  KARINA            POLICE OFFICER            POLICE   
3  AARON,  KIMBERLEI R  CHIEF CONTRACT EXPEDITER  GENERAL SERVICES   
4  ABAD JR,  VICENTE M         CIVIL ENGINEER IV       WATER MGMNT   

   Employee Annual Salary  
0                 88968.0  
1                 80778.0  
2                 80778.0  
3                 84780.0  
4                104736.0  


In [ ]:
# Faça a somatória da coluna Employee Annual Salary


In [25]:
import pandas as pd

# Carregando o arquivo salarios.csv
df_salarios = pd.read_csv('salarios.csv', sep=',')

# Removendo o caractere $ e convertendo para float
df_salarios['Employee Annual Salary'] = df_salarios['Employee Annual Salary'].str.replace('$', '', regex=False).astype(float)

# Calculando a somatória da coluna Employee Annual Salary
soma_salarios = df_salarios['Employee Annual Salary'].sum()

# Exibindo o resultado da somatória
print(f'A somatória da coluna Employee Annual Salary é: {soma_salarios}')


A somatória da coluna Employee Annual Salary é: 2547690152.24


# Fim